name: Autopep8

on: [push, pull_request]

jobs:
  autopep8:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install autopep8
      run: |
        python -m pip install --upgrade pip
        pip install autopep8

    - name: Run autopep8
      run: |
        autopep8 --in-place --recursive .
      continue-on-error: true