name: Python Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Specify the Python version you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov codecov  # Install pytest-cov and codecov

      - name: Run tests with coverage
        run: |
          pytest --cov=.  # Run tests with coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2