name: Static Analysis

on: [push, pull_request]

jobs:
  static-analysis:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install autopep8 pyflakes pylint

    - name: Run autopep8
      run: |
        autopep8 --in-place --recursive .
      continue-on-error: true

    - name: Run pyflakes
      run: |
        pyflakes .
      continue-on-error: true

    - name: Run pylint
      run: |
        pylint $(git ls-files '*.py')
      continue-on-error: true