name: Static Analysis

on: [push, pull_request]

jobs:
  autopep8:
    name: Autopep8
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install autopep8
      run: |
        python -m pip install --upgrade pip
        pip install autopep8

    - name: Run autopep8
      run: |
        autopep8 --in-place --recursive .
      continue-on-error: true

  pyflakes:
    name: Pyflakes
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install pyflakes
      run: |
        python -m pip install --upgrade pip
        pip install pyflakes

    - name: Run pyflakes
      run: |
        pyflakes .
      continue-on-error: true

  pylint:
    name: Pylint
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install pylint
      run: |
        python -m pip install --upgrade pip
        pip install pylint

    - name: Run pylint
      run: |
        pylint $(git ls-files '*.py')
      continue-on-error: true